version: 0.1 ({build})

skip_branch_with_pr: true

os:
  - Visual Studio 2017

platform:
  - x64

matrix:
  fast_finish: true  # Stop remaining jobs after a job failure

configuration:
  - Release

clone_folder: C:\CubbyDNN

install:
  - git submodule update --init
  - ps: |
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017 Win64"

before_build:
  - md C:\CubbyDNN\build
  - cd C:\CubbyDNN\build
  - cmake .. -G "%CMAKE_GENERATOR%"

build:
  project: C:\CubbyDNN\build\CubbyDNN.sln
  parallel: true
  verbosity: normal

after_build:
  - C:\CubbyDNN\build\bin\Release\UnitTests.exe